In [1]:
file = 'day_15.csv'
header = ['col'+str(i) for i in range (1,41)]
with open(file) as f:
    nrows_file = sum(1 for line in f)
nrows_file

2834692

### cudf

In [2]:
import cudf
%time dfcudf = cudf.read_csv(file, delimiter='\t', names=header, nrows = nrows_file)
dfcudf

CPU times: user 2.43 s, sys: 999 ms, total: 3.43 s
Wall time: 3.44 s

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col31,col32,col33,col34,col35,col36,col37,col38,col39,col40
0,0,2.0,9.0,<NA>,1.0,<NA>,0.0,0.0,3,1,...,1f7fc70b,b8170bba,9512c20b,31a9f3b3,228aee9b,b74c6548,59f9dd38,165fbf32,0b3c06d0,2ccea557
1,0,12.0,166.0,3.0,3.0,<NA>,1.0,0.0,1,3,...,d20856aa,b6bc86c5,108a0699,e7ef7c20,113b1789,670bb82a,0c427c16,fc6fc912,991321ea,2997ef88
2,0,1.0,66.0,<NA>,<NA>,<NA>,<NA>,<NA>,2,0,...,753da5f3,b8170bba,9512c20b,1a0af648,13b96cbc,3f2bae22,209c86ee,165fbf32,ff654802,2ccea557
3,0,1.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,1,...,1f7fc70b,b8170bba,7a7178b2,0da1444b,cf12754e,af22e988,c483d0dd,75350c8a,57e36578,ed10571d
4,0,2.0,<NA>,4.0,4.0,<NA>,7.0,0.0,59,4,...,d20856aa,a1eb1511,9512c20b,44fa1260,c59d0ef0,c41079d6,38d2af52,37dcf7a2,ff654802,b757e957
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2834687,0,7.0,433.0,4.0,41.0,75.0,0.0,10.0,84,8,...,d20856aa,b8170bba,cc7a7d35,156cbe87,96fbe197,15562d5d,d3df7183,4f008751,cdc3217e,e1be5ef2
2834688,0,79.0,1495.0,11.0,<NA>,4.0,0.0,0.0,263,16,...,d20856aa,b8170bba,cc7a7d35,156cbe87,96fbe197,15562d5d,d3df7183,5dea4c3e,30436bfc,e1be5ef2
2834689,0,11.0,98.0,8.0,7.0,<NA>,102.0,0.0,2,13,...,1f7fc70b,b6bc86c5,9512c20b,6ff6bffb,0fce3a61,0c45eace,3635180f,0604d44b,0b3c06d0,b757e957
2834690,0,48.0,1.0,22.0,35.0,4.0,0.0,0.0,2,37,...,753da5f3,b8170bba,139221a3,adeb2098,b24ec89e,2345cbe7,da233769,cb97d34d,30436bfc,2ccea557
2834691,0,3.0,7.0,3.0,<NA>,3.0,0.0,0.0,42,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [3]:
dfcudfpandas = dfcudf.to_pandas()
%time type(dfcudfpandas)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.96 µs

pandas.core.frame.DataFrame

In [4]:
%time dfcudfpandas

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 5.48 µs

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col31,col32,col33,col34,col35,col36,col37,col38,col39,col40
0,0,2.0,9.0,NaN,1.0,NaN,0.0,0.0,3,1,...,1f7fc70b,b8170bba,9512c20b,31a9f3b3,228aee9b,b74c6548,59f9dd38,165fbf32,0b3c06d0,2ccea557
1,0,12.0,166.0,3.0,3.0,NaN,1.0,0.0,1,3,...,d20856aa,b6bc86c5,108a0699,e7ef7c20,113b1789,670bb82a,0c427c16,fc6fc912,991321ea,2997ef88
2,0,1.0,66.0,NaN,NaN,NaN,NaN,NaN,2,0,...,753da5f3,b8170bba,9512c20b,1a0af648,13b96cbc,3f2bae22,209c86ee,165fbf32,ff654802,2ccea557
3,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2,1,...,1f7fc70b,b8170bba,7a7178b2,0da1444b,cf12754e,af22e988,c483d0dd,75350c8a,57e36578,ed10571d
4,0,2.0,NaN,4.0,4.0,NaN,7.0,0.0,59,4,...,d20856aa,a1eb1511,9512c20b,44fa1260,c59d0ef0,c41079d6,38d2af52,37dcf7a2,ff654802,b757e957
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2834687,0,7.0,433.0,4.0,41.0,75.0,0.0,10.0,84,8,...,d20856aa,b8170bba,cc7a7d35,156cbe87,96fbe197,15562d5d,d3df7183,4f008751,cdc3217e,e1be5ef2
2834688,0,79.0,1495.0,11.0,NaN,4.0,0.0,0.0,263,16,...,d20856aa,b8170bba,cc7a7d35,156cbe87,96fbe197,15562d5d,d3df7183,5dea4c3e,30436bfc,e1be5ef2
2834689,0,11.0,98.0,8.0,7.0,NaN,102.0,0.0,2,13,...,1f7fc70b,b6bc86c5,9512c20b,6ff6bffb,0fce3a61,0c45eace,3635180f,0604d44b,0b3c06d0,b757e957
2834690,0,48.0,1.0,22.0,35.0,4.0,0.0,0.0,2,37,...,753da5f3,b8170bba,139221a3,adeb2098,b24ec89e,2345cbe7,da233769,cb97d34d,30436bfc,2ccea557
2834691,0,3.0,7.0,3.0,NaN,3.0,0.0,0.0,42,0,...,None,None,None,None,None,None,None,None,None,None

### blazingsql

In [5]:
from blazingsql import BlazingContext
%time bc = BlazingContext()
%time bc.create_table('CTR', file, delimiter='\t', names=header, nrows = nrows_file)
%time dfsql = bc.sql('SELECT * FROM CTR')
dfsql

BlazingContext ready
CPU times: user 906 ms, sys: 82.9 ms, total: 989 ms
Wall time: 456 ms
CPU times: user 32.9 ms, sys: 373 ms, total: 406 ms
Wall time: 406 ms
CPU times: user 1.73 s, sys: 561 ms, total: 2.3 s
Wall time: 1.53 s

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col31,col32,col33,col34,col35,col36,col37,col38,col39,col40
0,0,2,9,<NA>,1,<NA>,0,0,3,1,...,1f7fc70b,b8170bba,9512c20b,31a9f3b3,228aee9b,b74c6548,59f9dd38,165fbf32,0b3c06d0,2ccea557
1,0,12,166,3,3,<NA>,1,0,1,3,...,d20856aa,b6bc86c5,108a0699,e7ef7c20,113b1789,670bb82a,0c427c16,fc6fc912,991321ea,2997ef88
2,0,1,66,<NA>,<NA>,<NA>,<NA>,<NA>,2,0,...,753da5f3,b8170bba,9512c20b,1a0af648,13b96cbc,3f2bae22,209c86ee,165fbf32,ff654802,2ccea557
3,0,1,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2,1,...,1f7fc70b,b8170bba,7a7178b2,0da1444b,cf12754e,af22e988,c483d0dd,75350c8a,57e36578,ed10571d
4,0,2,<NA>,4,4,<NA>,7,0,59,4,...,d20856aa,a1eb1511,9512c20b,44fa1260,c59d0ef0,c41079d6,38d2af52,37dcf7a2,ff654802,b757e957
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2834687,0,7,433,4,41,75,0,10,84,8,...,d20856aa,b8170bba,cc7a7d35,156cbe87,96fbe197,15562d5d,d3df7183,4f008751,cdc3217e,e1be5ef2
2834688,0,79,1495,11,<NA>,4,0,0,263,16,...,d20856aa,b8170bba,cc7a7d35,156cbe87,96fbe197,15562d5d,d3df7183,5dea4c3e,30436bfc,e1be5ef2
2834689,0,11,98,8,7,<NA>,102,0,2,13,...,1f7fc70b,b6bc86c5,9512c20b,6ff6bffb,0fce3a61,0c45eace,3635180f,0604d44b,0b3c06d0,b757e957
2834690,0,48,1,22,35,4,0,0,2,37,...,753da5f3,b8170bba,139221a3,adeb2098,b24ec89e,2345cbe7,da233769,cb97d34d,30436bfc,2ccea557
2834691,0,3,7,3,<NA>,3,0,0,42,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [6]:
dfsql.loc[(dfsql['col1'] != 0)]

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col31,col32,col33,col34,col35,col36,col37,col38,col39,col40
15,1,10,258,1,<NA>,3,0,0,7,5,...,d20856aa,b8170bba,9512c20b,febfd863,a3323ca1,c8e1ee56,1752e9e8,2017de87,ff654802,962813c6
55,1,1,24,<NA>,16,8,<NA>,0,5,0,...,753da5f3,a1eb1511,9512c20b,58213c15,ac6b4433,978c1d05,d5d0f074,641cdf7e,337b81aa,2ccea557
116,1,<NA>,12,<NA>,0,<NA>,0,0,1,0,...,<NA>,b8170bba,9512c20b,<NA>,<NA>,<NA>,<NA>,be8bb7d8,cdc3217e,2ccea557
128,1,<NA>,139,<NA>,43,28,0,0,449,0,...,<NA>,b8170bba,9512c20b,e1e19a59,c23080a7,0b9ac5b9,<NA>,007c1d72,337b81aa,ed10571d
275,1,5,64,2,1,18,3,0,0,4,...,d20856aa,b8170bba,9512c20b,e589a1e7,c6af11c1,7be11f3a,38d2af52,4b3ebb1b,30436bfc,b757e957
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2834568,1,1,1292,<NA>,<NA>,2,0,0,209,3,...,d20856aa,d75a120f,9512c20b,7277423d,71e41333,6bfdb903,ee7860e8,f99b2996,ff654802,b757e957
2834585,1,3,4,2,6,1,0,0,5,3,...,<NA>,b8170bba,9512c20b,fe12fdf5,d3bc6a7f,129d1ca8,<NA>,d04b7a41,ff654802,2ccea557
2834597,1,<NA>,471,<NA>,<NA>,2,0,0,12,3,...,<NA>,7232d217,9512c20b,ef426d46,0683bc6f,6e86ac23,<NA>,af7635ee,30436bfc,b757e957
2834609,1,2,2065,2,<NA>,<NA>,0,0,35,9,...,<NA>,a1eb1511,09c8c22c,47849e55,73b3f46d,d994ba60,<NA>,215866f4,30436bfc,b757e957
2834628,1,7,1920,16,32,5,1,0,38,42,...,<NA>,b8170bba,09c8c22c,e19f94a4,7fe52a5b,86fab3ad,<NA>,9e2bb29a,ff654802,7c94c9ef